const DojoData = [
    {
        id: "1001",
        club: "Hombu Dojo",
        addressStreet: "Krijgsbaan",
        addressNumber: "39",
        addressCity: "Mortsel",
        addressPostalCode: "2640",
        province: "Province d'Anvers",
        addressCountry: "Belgique",
        contactMail: "stephane.castrique@gmail.com",
        phone: "0032 478 30 16 13",
        website: "http://www.honbu-dojo.be",
        chiefInstructeur: "Stéphane Castrique",
        chiefInstructeurRank: "6e Dan",
        instructeur: "Sabine Castrique",
        ChiefInstructeurPic: "",
        scheduleMonday: ["Lundi: ", "19h30 à 21h00 Adultes (+13 ans) UNIQUEMENT ceintures noires"],
        scheduleTuesday: ["Mardi: ", "19h30 à 21h00 UNIQUEMENT ceintures noires"],
        scheduleWednesday: ["Mercredi: ", "14h00 à 15h00 Débutants (+6 ans) de 15h00 à 16h00 Enfants ceinture orange et plus"],
        scheduleThursday: ["Jeudi: ",  "19h30 à 21h00 Adultes (+13 ans)"],
        scheduleFriday: ["Vendredi:", "19h30 à 21h00 Entraînement Kumite (minimum 12 ans et ceinture bleue)"],
        scheduleSaturday: [ , ],
        scheduleSunday: [
       "Dimanche", "10:00 à 11:00 Enfants & Adultes Débutants Classe générale", 
        "11:00 à 12:00 Enfants & Adultes Ceinture orange et plus Classe générale",
        "12:00 à 13:30 Enfants & Adultes Ceintures brunes et noires Classe générale"
],
        ClubEvent: "",
        cover: "images/senseis/stephaneCastrique.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub2",
        club: "Poseidon",
        addressStreet: "Av. des Vaillants",
        addressNumber: "4",
        addressCity: "Woluwe-Saint-Lambert",
        addressPostalCode: "1200",
        province: "Province Bruxelles-Capital",
        contactMail: "skif.poseidon@hotmail.com",
        addressCountry: "Belgium",
        phone: "0032 488 25 65 71",
        website: "http://skif-poseidon.com",
        chiefInstructeur: "Achour Bakkioui",
        chiefInstructeurRank: "7e Dan",
        instructeur: [
            "Eric Vermeulen",
            "Alessandro Notaragello",
            "Stewart Napier",
            "Jean-Michel Hecq",
            "Hung Nguyen",
        ],
        ChiefInstructeurPic: "",
        schedule: [
            "Lundi de 21:00 à 22:00",
            "Mecredi:	[de 18:45 à 19:45 Enfants (de 9 à 12 ans) de 19:45 à 20:45	Enfants (de 13 à 16 ans) de 20:45 à 22:00 3ième Kyū & plus",
            "Vendredi	de 21:00 à 22:00	Adultes (+17 ans)",
            "Samedi	de 14:30 à 15:30	Enfants (de 6 à 8 ans) de 15:30 à 16:45	Enfants (de 9 à 12 ans) de 16:45 à 18:00	Enfants (de 13 à 16 ans)",
            "Dimanche de 10:00 à 11:00	7ième Kyū & plus (KUMITE)  de 11:00 à 12:00	7ième Kyū & plus (KATA)",
        ],
        ClubEvent: "",
        cover: "images/Senseis/achourBakkioui.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub3",
        club: "Seikukai",
        addressStreet: "Waterloo Tennis Bld Henri Rolin",
        addressNumber: "5",
        addressCity: "Waterloo",
        addressPostalCode: "1410",
        province: "Province du Brabant Wallon",
        contactMail: "daniel.kina@skynet.be",
        addressCountry: "Belgium",
        phone: "0032 475 56 40 52",
        website: "",
        chiefInstructeur: "Daniel Kina",
        chiefInstructeurRank: "5e Dan",
        instructeur: ["Pierre Deridder"],
        ChiefInstructeurPic: "",
        schedule: [
            "Mecredi	de 17:00 à 18:00	Enfants (Tous les grades) de 18:00 à 19:00	Adultes (Tous les grades)",
            "Samedi	de 14:00 à 15:00	Enfants (Tous les grades) de 15:00 à 16:30	Adultes (Tous les grades)",
            "Dimanche	de 10:00 à 11:00	Enfants (Tous les grades) de 11:00 à 12:00	Adultes (Tous les grades) de 12:00 à 12:30	Adultes (à partir de 4ième Kyū)",
        ],
        ClubEvent: "",
        cover: "/images/Senseis/DanielKina.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub4",
        club: "ICHŌ",
        addressStreet: "Solleveld",
        addressNumber: "11",
        addressCity: "Dilbeek",
        addressPostalCode: "1700",
        province: "Vlaams-Brabant",
        contactMail: "icho_sport@hotmail.com",
        addressCountry: "Belgium",
        phone: "0032 479 28 77 69",
        website: "",
        chiefInstructeur: "Van Der Stappen Pim",
        chiefInstructeurRank: "6e Dan",
        instructeur: [],
        ChiefInstructeurPic: "",
        schedule: [
            "Mardi	de 17:15 à 18:15	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 18:15 à 19:15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 19:15 à 20:45	Adultes   (+12 ans)",
            "Vendredi 	de 14:30 à 15:30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 15:30 à 16:30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 16:30 à 18:00	Adultes   (+12 ans)",
        ],
        ClubEvent: "",
        cover: "/images/Senseis/pimVanDerStrappen.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub5",
        club: "TSK Eghezee",
        addressStreet: "Rue de la gare",
        addressNumber: "5",
        addressCity: "Eghezee",
        addressPostalCode: "5310",
        province: "Province de Namur",
        contactMail: "karateeghezee@gmail.com",
        addressCountry: "Belgium",
        phone: "0032 495 32 19 00",
        website: "http://www.karateeghezee.com",
        chiefInstructeur: "Stephan Van Lerberghe",
        chiefInstructeurRank: "5e Dan",
        instructeur: [],
        ChiefInstructeurPic: "",
        schedule: [
            "Mecredi	de 17:15 à 18:15	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 18:15 à 19:15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 19:15 à 20:45	Adultes   (+12 ans)",
            "Samedi	de 14:30 à 15:30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 15:30 à 16:30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 16:30 à 18:00	Adultes   (+12 ans)",
        ],
        ClubEvent: "",
        cover: "/images/Senseis/StephanVL.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub6",
        club: "Sen No Sen",
        addressStreet: "Rue Wilson",
        addressNumber: "36",
        addressCity: "Dolhain",
        addressPostalCode: "4830",
        province: "Province du Limbourg",
        contactMail: "info@sennosen.be",
        addressCountry: "Belgium",
        phone: "0032 495 51 94 05",
        website: "www.sennosen.be",
        chiefInstructeur: "Bernard Delhez",
        chiefInstructeurRank: "5e Dan",
        instructeur: ["Sylvie Hellweg", "Jérémy Delhez"],
        ChiefInstructeurPic: "",
        schedule: [
            "Mecredi	de 17:15 à 18:15	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 18:15 à 19:15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 19:15 à 20:45	Adultes   (+12 ans)",
            "Samedi	de 14:30 à 15:30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 15:30 à 16:30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 16:30 à 18:00	Adultes   (+12 ans)",
        ],
        ClubEvent: "",
        cover: "images/Senseis/bernardDelhez.jpg",
        pictures: ["", "", ""],
    },
];
export default DojoData;

/*
        scheduleMonday: "",
        scheduleTuesday:"",
        scheduleWednesday:"",
        scheduleThursday:"",
        scheduleFriday:"",
        scheduleSaturday:"",
        scheduleSunday:""
*/
