const DojoData = [
    {
       "id": "1001",
        club: "Hombu Dojo",
        addressStreet: "Krijgsbaan",
        addressNumber: "39",
        addressCity: "Mortsel",
        addressPostalCode: "2640",
        province: "Province d'Anvers",
        addressCountry: "Belgique",
        contactMail: ["Email: ", "stephane.castrique@gmail.com"],
        phone: ["Téléphone: ", "0032 478 30 16 13"],
        website: ["Site Web: ", "http://www.honbu-dojo.be"],
        chiefInstructeurName: "Stéphane Castrique",
        chiefInstructeurRank: "6e Dan",
        ChiefInstructeurPosition: "Chef Instructeur",
        chiefInstructeurPic: "/images/Senseis/Castrique-Stephane.jpeg",
        instructeurs: {
            instructeur: {
                instructeurName: "Sabine Castrique",
                instructeurRank: "5e Dan",
                instructeurPic: "/images/Senseis/sabineCastrique.jpg",
                instructeurPosition: "Instructeur",
            },
        },
        scheduleMonday: ["Lundi: ", "19h30 à 21h00 Adultes (+13 ans) UNIQUEMENT ceintures noires"],
        scheduleTuesday: ["Mardi: ", "19h30 à 21h00 UNIQUEMENT ceintures noires"],
        scheduleWednesday: [
            "Mercredi: ",
            "14h00 à 15h00 Débutants (+6 ans) de 15h00 à 16h00 Enfants ceinture orange et plus",
        ],
        scheduleThursday: ["Jeudi: ", "19h30 à 21h00 Adultes (+13 ans)"],
        scheduleFriday: [
            "Vendredi:",
            "19h30 à 21h00 Entraînement Kumite (minimum 12 ans et ceinture bleue)",
        ],
        scheduleSaturday: [,],
        scheduleSunday: [
            "Dimanche",
            "10:00 à 11:00 Enfants & Adultes Débutants Classe générale",
            "11:00 à 12:00 Enfants & Adultes Ceinture orange et plus Classe générale",
            "12:00 à 13:30 Enfants & Adultes Ceintures brunes et noires Classe générale",
        ],
        ClubEvent: "",
        cover: "images/senseis/stephaneCastrique.jpg",
        pictures: [
            "/images/HombuDojo/test6.jpg",
            "/images/HombuDojo/test5.jpg",
            "/images/HombuDojo/test7.jpg",
        ],
    },
    {
        id: "1002",
        club: "Poseidon",
        addressStreet: "Av. des Vaillants",
        addressNumber: "4",
        addressCity: "Woluwe-Saint-Lambert",
        addressPostalCode: "1200",
        province: "Province Bruxelles-Capital",
        contactMail: ["Email: ", "skif.poseidon@hotmail.com"],
        addressCountry: "Belgium",
        phone: ["Téléphone: ","0032 488 25 65 71"],
        website: ["Site Web: ", "http://skif-poseidon.com"],
       


        chiefInstructeurRank: "7e Dan",
        chiefInstructeurName: "Achour Bakkioui",
        ChiefInstructeurPosition: "Chef Instructeur",
        chiefInstructeurPic: "/images/Poseidon/AchourB.jpg",
        instructeurs: {
            instructeur: {
                instructeurName: "Eric Vermeulen",
                instructeurRank: "6e Dan",
                instructeurPic: "/images/Poseidon/EricVermeulen.jpg",
                instructeurPosition: "Instructeur",
            },
            instructeur2: {
                instructeurName2: "Alexandro Notarangelo",
                instructeurRank2: "5e Dan",
                instructeurPic2: "/images/Poseidon/alessandroNotarangelo.jpg",
                instructeurPosition2: "Instructeur",
            },
        },

        scheduleMonday: ["Lundi: ", "21h00 à 20h00 Adultes (+18 ans) UNIQUEMENT"],
        scheduleTuesday: [,],
        scheduleWednesday: [
            "Mercredi: ",
            "18h45 à 19h45 Enfants (9 à 12 ans)",
            "19h45 à 20h45 Enfants (13 à 17 ans)",
            "20h45 à 22h00 Enfants 18 ans et plus min 5e Kyu – bleu ",
        ],
        scheduleThursday: ["Jeudi: ", "20h00 à 21h30 Kumité"],
        scheduleFriday: ["Vendredi:", "21h00 à 22h00 Entraînement min 18 ans"],
        scheduleSaturday: [
            "Samedi:",
            "13h30 à 14h30 de 6 à 7 ans",
            "14h30 à 15h30 de 8 à 9 ans",
            "15h30 à 16h45 de 10 à 12 ans",
            "16h45 à 18h00 de 13 à 17 ans",
        ],
        scheduleSunday: [
            "Dimanche",
            "10:00 à 11:00 Kumite 10 ans et + 7è kyu (orange) et + ",
            "11:00 à 12:00 Kata – 10 ans et + 7è kyu (orange) et +",
        ],
        ClubEvent: "",
        cover: "images/Senseis/achourBakkioui.jpg",
        pictures: [
            "/images/Poseidon/KanazawaBrothersAchour.jpg",
            "/images/Poseidon/poseidon2.jpg",
            "/images/Poseidon/poseidonStageKumite.jpg",
        ],
        center: {
            lat: "50.843191",
            lng: "4.4267367"
          }
    },
    {
        id: "SkifClub3",
        club: "Seikukai",
        addressStreet: "Waterloo Tennis Bld Henri Rolin",
        addressNumber: "5",
        addressCity: "Waterloo",
        addressPostalCode: "1410",
        province: "Province du Brabant Wallon",
        contactMail: "daniel.kina@skynet.be",
        addressCountry: "Belgium",
        phone: "0032 475 56 40 52",
        website: "",
        chiefInstructeur: "Daniel Kina",
        chiefInstructeurRank: "5e Dan",
        instructeur: ["Pierre Deridder"],
        ChiefInstructeurPic: "",
        schedule: [
            "Mecredi	de 17:00 à 18:00	Enfants (Tous les grades) de 18:00 à 19:00	Adultes (Tous les grades)",
            "Samedi	de 14:00 à 15:00	Enfants (Tous les grades) de 15:00 à 16:30	Adultes (Tous les grades)",
            "Dimanche	de 10:00 à 11:00	Enfants (Tous les grades) de 11:00 à 12:00	Adultes (Tous les grades) de 12:00 à 12:30	Adultes (à partir de 4ième Kyū)",
        ],
        ClubEvent: "",
        cover: "/images/Senseis/DanielKina.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub4",
        club: "ICHŌ",
        addressStreet: "Solleveld",
        addressNumber: "11",
        addressCity: "Dilbeek",
        addressPostalCode: "1700",
        province: "Vlaams-Brabant",
        contactMail: "icho_sport@hotmail.com",
        addressCountry: "Belgium",
        phone: "0032 479 28 77 69",
        website: "",
        chiefInstructeur: "Van Der Stappen Pim",
        chiefInstructeurRank: "6e Dan",
        instructeur: [],
        ChiefInstructeurPic: "",
        schedule: [
            "Mardi	de 17:15 à 18:15	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 18:15 à 19:15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 19:15 à 20:45	Adultes   (+12 ans)",
            "Vendredi 	de 14:30 à 15:30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 15:30 à 16:30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 16:30 à 18:00	Adultes   (+12 ans)",
        ],
        ClubEvent: "",
        cover: "/images/Senseis/pimVanDerStrappen.jpg",
        src: "https://scontent-rtl.akamaized.net/GED/10160000/10168100/10168109_700x0.webp",
    },
    {
        id: "SkifClub5",
        club: "TSK Eghezee",
        addressStreet: "Rue de la gare",
        addressNumber: "5",
        addressCity: "Eghezee",
        addressPostalCode: "5310",
        province: "Province de Namur",
        contactMail: "karateeghezee@gmail.com",
        addressCountry: "Belgium",
        phone: "0032 495 32 19 00",
        website: "http://www.karateeghezee.com",
        chiefInstructeur: "Stephan Van Lerberghe",
        chiefInstructeurRank: "5e Dan",
        instructeur: [],
        ChiefInstructeurPic: "",
        schedule: [
            "Mecredi	de 17:15 à 18:15	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 18:15 à 19:15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 19:15 à 20:45	Adultes   (+12 ans)",
            "Samedi	de 14:30 à 15:30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 15:30 à 16:30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 16:30 à 18:00	Adultes   (+12 ans)",
        ],
        ClubEvent: "",
        cover: "/images/Senseis/StephanVL.jpg",
        pictures: ["", "", ""],
    },
    {
        id: "SkifClub6",
        club: "Sen No Sen",
        addressStreet: "Rue Wilson",
        addressNumber: "36",
        addressCity: "Dolhain",
        addressPostalCode: "4830",
        province: "Province du Limbourg",
        contactMail: "info@sennosen.be",
        addressCountry: "Belgium",
        phone: "0032 495 51 94 05",
        website: "www.sennosen.be",
        chiefInstructeur: "Bernard Delhez",
        chiefInstructeurRank: "5e Dan",
        instructeur: ["Sylvie Hellweg", "Jérémy Delhez"],
        ChiefInstructeurPic: "",
        schedule: [
            "Mecredi	de 17:15 à 18:15	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 18:15 à 19:15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 19:15 à 20:45	Adultes   (+12 ans)",
            "Samedi	de 14:30 à 15:30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū de 15:30 à 16:30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū de 16:30 à 18:00	Adultes   (+12 ans)",
        ],
        ClubEvent: "",
        cover: "images/Senseis/bernardDelhez.jpg",
        pictures: ["", "", ""],
    },
];
export default DojoData;

/*
        scheduleMonday: "",
        scheduleTuesday:"",
        scheduleWednesday:"",
        scheduleThursday:"",
        scheduleFriday:"",
        scheduleSaturday:"",
        scheduleSunday:""
*/
