const DojoData = [
	{
		id: "1001",
		club: "Hombu Dojo",
		address: [
			{
				street: "Krijgsbaan",
				number: "39",
				city: "Mortsel",
				postCode: "2640",
				province: "Provincie Antwerpen",
				country: "België",
				lat: "51.1757656",
				lng: "4.4539556",
			},
		],
		town: "Mortsel",
		contact: [
			{
				email: " stephane.castrique@gmail.com",
				phone: "0032 478 30 16 13",
				website: "http://www.honbu-dojo.be",
			},
		],
		socialNetwork: {
			facebook: "",
			instagram: "",
			youtube: "",
			tiktok: "",
			snapchat: "",
			pinterest: "",
			twitter: "",
		},
		chiefInstructeur: {
			name: "Stéphane Castrique",
			rank: "6e Dan",
			position: "Hoofdinstructeur",
			pic: "/images/Dojos/HombuDojo/Castrique-Stephane.jpeg",
		},
		instructeurs: [
			{
				name: "Sabine Castrique",
				rank: "5e Dan",
				pic: "/images/Dojos/HombuDojo/sabineCastrique.jpg",
				position: "Instructeur",
			},
		],
		schedules: [
			{
				monday: ["Maandag: ", "Volwassenen (+13 jaar) GÉÉN Zwarte gordels"],
				tuesday: ["Dinsdag: ", "ALLÉÉN Zwarte gordels"],
				wednesday: ["Woensdag: ", "Beginners (+6 jaar)"],
				thursday: ["Donderdag: ", "Volwassenen (+13 jaar)"],
				friday: ["Vrijdag: ", "Kumite training (minimum 12 jaar & Blauwe gordel)"],
				saturday: [],
				sunday: [
					"Zondag: ",
					"van 10:00 tot 11:00 Kinderen & Volwassenen Beginners - Algemene les",
					"van 11:00 tot 12:00 Kinderen & Volwassenen Oranje gordel en hoger Algemene les",
					"van 12:00 tot 13:30 Kinderen & Volwassenen Bruine & Zwarte gordels Algemene les",
				],
			},
		],
		ClubEvent: "",
		cover: "images/Senseis/stephaneCastrique.jpg",
		pictures: ["/images/Dojos/HombuDojo/test6.jpg", "/images/Dojos/HombuDojo/test5.jpg", "/images/Dojos/HombuDojo/test7.jpg"],
	},
	{
		id: "1002",
		club: "Poseidon",
		address: [
			{
				street: "Av. des Vaillants",
				number: "4",
				city: "Woluwe-Saint-Lambert",
				postCode: "1200",
				province: "Province Bruxelles-Capitale",
				country: "Belgique",
				lat: "50.8435794",
				lng: "4.4194461",
			},
		],
		town: "Woluwe-Saint-Lambert",
		contact: [
			{
				email: "skif.poseidon@hotmail.com",
				phone: "0032 488 25 65 71",
				website: "http://skif-poseidon.com",
			},
		],
		socialNetwork: {
			facebook: "",
			instagram: "",
			youtube: "",
			tiktok: "",
			snapchat: "",
			pinterest: "",
			twitter: "",
		},
		chiefInstructeur: {
			name: "Achour Bakkioui",
			rank: "7e Dan",
			position: "Chef Instructeur",
			pic: "/images/Dojos/Poseidon/AchourB.jpg",
		},
		instructeurs: [
			{
				name: "Eric Vermeulen",
				rank: "6e Dan",
				pic: "/images/Dojos/Poseidon/EricVermeulen.jpg",
				position: "Instructeur",
			},
			{
				name: "Alexandro Notarangelo",
				rank: "5e Dan",
				pic: "/images/Dojos/Poseidon/alessandroNotarangelo.jpg",
				position: "Instructeur",
			},
			{
				name: "Stewart Napier",
				rank: "4e Dan",
				pic: "/images/Dojos/Poseidon/StewartNapier.jpg",
				position: "Instructeur",
			},
			{
				name: "Jean-Michel Hecq",
				rank: "4e Dan",
				pic: "/images/Dojos/Poseidon/JmH.jpg",
				position: "Instructeur",
			},
			{
				name: "Hung",
				rank: "4e Dan",
				pic: "/images/Dojos/Poseidon/Hung.jpg",
				position: "Instructeur",
			},
		],
		schedules: [
			{
				monday: ["Lundi: ", "21h00 à 22h00 Adultes (+18 ans) UNIQUEMENT"],
				tuesday: [],
				wednesday: [
					"Mercredi: ",
					"18h45 à 19h45 Enfants (9 à 12 ans)",
					"19h45 à 20h45 Enfants (13 à 17 ans)",
					"20h45 à 22h00 Enfants 18 ans et plus min 5e Kyu – bleu ",
				],
				thursday: ["Jeudi: ", "20h00 à 21h30 Kumite"],
				friday: ["Vendredi: ", "21h00 à 22h00 Entraînement min 18 ans"],
				saturday: ["Samedi: ", "13h30 à 14h30 de 6 à 7 ans", "14h30 à 15h30 de 8 à 9 ans", "15h30 à 16h45 de 10 à 12 ans", "16h45 à 18h00 de 13 à 17 ans"],
				sunday: ["Dimanche: ", "10:00 à 11:00 Kumite 10 ans et + 7è kyu (orange) et + ", "11:00 à 12:00 Kata – 10 ans et + 7è kyu (orange) et +"],
			},
		],
		ClubEvent: "",
		cover: "images/Senseis/achourBakkioui.jpg",
		pictures: ["/images/Dojos/Poseidon/KanazawaBrothersAchour.jpg", "/images/Dojos/Poseidon/poseidon2.jpg", "/images/Dojos/Poseidon/poseidonStageKumite.jpg"],
	},
	{
		id: "SkifClub3",
		club: "Seikukai",
		address: [
			{
				street: "Waterloo Tennis Bld Henri Rolin",
				number: "5",
				city: "Waterloo",
				postCode: "1410",
				province: "Province du Brabant Wallon",
				country: "Belgique",
				lat: "50.7112846",
				lng: "4.3967179",
			},
		],
		town: "Waterloo",
		contact: [
			{
				email: "daniel.kina@skynet.be",
				phone: "0032 475 56 40 52",
				website: "",
			},
		],
		socialNetwork: [
			{
				facebook: "",
				instagram: "",
				youtube: "",
				tiktok: "",
				snapchat: "",
				pinterest: "",
				twitter: "",
			},
		],
		chiefInstructeur: {
			name: "Daniel Kina",
			rank: "5e Dan",
			pic: "/images/Dojos/Seikukai/Kina-Daniel.jpg",
			position: "Chef Instructeur",
		},
		instructeurs: [
			{
				name: "Pierre Deridder",
				rank: "5e Dan",
				pic: "/images/Dojos/Seikukai/pierreDR.jpg",
				position: "Instructeur",
			},
		],
		schedules: [
			{
				monday: [],
				tuesday: [],
				wednesday: ["Mercredi: ", "de 17h00 à 18h00	Enfants (Tous les grades)", "de 18h00 à 19h00	Adultes (Tous les grades)"],
				thursday: [],
				friday: [],
				saturday: ["Samedi: ", "de 14h00 à 15h00	Enfants (Tous les grades)", "de 15h00 à 16h30	Adultes (Tous les grades)"],
				sunday: [
					"Dimanche: ",
					"10:00 à 11:00 Enfants (Tous les grades)",
					"11:00 à 12:00 Adultes (Tous les grades)",
					"12:00 à 12:30 Adultes (à partir de 4ième Kyū)",
				],
			},
		],
		ClubEvent: "",
		cover: "/images/Senseis/DanielKina.jpg",
		pictures: ["/images/posters/K1.jpg", "/images/posters/K2.jpg", "/images/posters/K3.jpg"],
	},
	{
		id: "SkifClub4",
		club: "Icho",
		address: [
			{
				street: "Solleveld",
				number: "11",
				city: "St-Martens-Bodegem",
				postCode: "1700",
				province: "Vlaams-Brabant",
				country: "België",
				lat: "50.8648689",
				lng: "4.2174683",
			},
			{
				street: "De kriebel Kerkstraat",
				number: "1",
				city: "Sint-Ulriks-Kapelle",
				postCode: "1700",
				province: "Vlaams-Brabant",
				country: "België",
				lat: "50.8789698",
				lng: "4.2158394",
			},
			{
				street: "Van Cauwelaertstraat",
				number: "26",
				city: "Ternat",
				postCode: "1740",
				province: "Vlaams-Brabant",
				country: "België",
				lat: "50.8688663",
				lng: "4.1711001",
			},
		],
		town: "Dilbeek - Ternat",
		contact: [
			{
				email: "icho_sport@hotmail.com",
				phone: "0032 479 28 77 69",
				website: "",
			},
		],
		socialNetwork: {
			facebook: "",
			instagram: "",
			youtube: "",
			tiktok: "",
			snapchat: "",
			pinterest: "",
			twitter: "",
		},
		chiefInstructeur: {
			name: "Van Der Stappen Pim",
			rank: "6e Dan",
			position: "Hoofdinstructeur",
			pic: "/images/Dojos/Icho/pimVDS.jpg",
		},
		instructeurs: [],
		schedules: [
			{
				monday: [],
				tuesday: [
					"Dinsdag: 'Solleveld, St-Martens-Bodegem'",
					"van 18h00 tot 19h00 Solleveld, St-Martens-Bodegem Jeugd (3 groepen)",
					"van 19h30 tot 21h00 Solleveld, St-Martens-Bodegem	Alle graden (Volwassenen)",
				],
				wednesday: [
					"Woensdag: 'Sportcentrum Ternat'",
					"van 17:00 tot 18h00 Kinderen vanaf 10de tot 7de Kyū ",
					"van 18h00 tot 19h00 Kinderen vanaf 6de Kyū ",
					"van 19h30 tot 21h00 Volwassenen alle graden ",
				],
				thursday: [],
				friday: [
					"Vrijdag: 'Sint-Ulriks-Kapelle'",
					"van 18h00 tot 19h00 Kerkstraat  Jeugd (3 groepen)",
					"van 19h30 tot 21h00 Kerkstraat Alle graden (Volwassenen)",
				],
				saturday: [],
				sunday: [],
			},
		],
		ClubEvent: "",
		cover: "/images/Senseis/pimVanDerStrappen.jpg",
		pictures: ["/images/posters/K1.jpg", "/images/posters/K2.jpg", "/images/posters/K3.jpg"],
	},
	{
		id: "SkifClub5",
		club: "TSK Eghezee",
		address: [
			{
				street: "Rue de la gare",
				number: "5",
				city: "Eghezee",
				postCode: "5310",
				province: "Province de Namur",
				country: "Belgique",
				lat: "50.5965928",
				lng: "4.9082173",
			},
		],
		town: "Eghezee",
		contact: [
			{
				email: "karateeghezee@gmail.com",
				phone: "0032 495 32 19 00",
				website: "http://www.karateeghezee.com",
			},
		],
		socialNetwork: [
			{
				facebook: "",
				instagram: "",
				youtube: "",
				tiktok: "",
				snapchat: "",
				pinterest: "",
				twitter: "",
			},
		],
		chiefInstructeur: {
			rank: "5e Dan",
			name: "Stephan Van Lerberghe",
			position: "Chef Instructeur",
			pic: "/images/Dojos/TSKEghezee/StefanVL.jpg",
		},
		instructeurs: [
			{
				name: "David ",
				rank: "2e Dan",
				pic: "/images/Dojos/TSKEghezee/davidG.jpg",
				position: "Instructeur",
			},
		],
		schedules: [
			{
				monday: [],
				tuesday: [],
				wednesday: [
					"Mercredi: ",
					"17h15 à 18h15 Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū",
					"18h15 à 19h15	Enfants (de 7 to 12 ans) à partir de 7ième Kyū",
					"19h15 à 20h45	Adultes   (+12 ans)",
				],
				thursday: [],
				friday: [],
				saturday: [
					"Samedi : ",
					"14h00 à 15h30	Enfants (de 7 à 12 ans) de 10ième à 8ième Kyū",
					"15h30 à 16h30	Enfants (de 7 to 12 ans) à partir de 7ième Kyū",
					"16h30 à 18h00	Adultes (+12 ans)",
				],
			},
		],
		ClubEvent: "",
		cover: "/images/Senseis/StephanVL.jpg",
		pictures: ["/images/Dojos/TSKEghezee/TSKE1.jpg", "/images/Dojos/TSKEghezee/TSKE2.jpg", "/images/Dojos/TSKEghezee/TSKE3.jpg"],
	},
	{
		id: "SkifClub6",
		club: "Sen No Sen",
		address: [
			{
				street: "Rue Wilson",
				number: "36",
				city: "Limbourg",
				postCode: "4830",
				province: "Province du Limbourg",
				country: "Belgique",
				lat: "50.6208009",
				lng: "5.9381384",
			},
			{
				street: "Place Saint-Georges",
				number: "53",
				city: "Limbourg",
				postCode: "4830",
				province: "Province du Limbourg",
				country: "Belgique",
				lat: "50.6115343",
				lng: "5.9407774",
			},
		],
		town: "Limbourg",
		contact: [
			{
				email: "info@sennosen.be",
				phone: "0032 495 51 94 05",
				website: "www.sennosen.be",
			},
		],
		socialNetwork: [
			{
				facebook: "",
				instagram: "",
				youtube: "",
				tiktok: "",
				snapchat: "",
				pinterest: "",
				twitter: "",
			},
		],
		chiefInstructeur: {
			rank: "5e Dan",
			name: "Bernard Delhez",
			position: "Chef Instructeur",
			pic: "/images/Dojos/SenNoSen/BernardD.jpg",
		},
		instructeurs: [
			{
				name: "Sylvie Hellweg",
				rank: "4e Dan",
				pic: "/images/Dojos/SenNoSen/SylvieH.jpg",
				position: "Instructeur",
			},
		],
		schedules: [
			{
				monday: ["Lundi: ", "Hall sportif de Limbourg", "18h30 à 19h30 Enfants", "19h30 à 21:00 Adultes"],
				tuesday: [],
				wednesday: [
					"Mercredi: ",
					"Ecole communale Limbourg",
					"18h30 à 19h30 Kata (10-9-8-7e Kyū)",
					"19h30 à 20h30 Kata (5e kyū < Centures noires)",
					"20h30 à 21h00 Kata ceintures noires",
				],
				thursday: [],
				friday: [],
				saturday: [
					"Samedi: ",
					"Hall sportif de Limbourg",
					"10h00 à 11h15 Enfants",
					"de 11h30 à 13h30 Adultes",
					"13h30 à 14h30 Kumite (entraînement à la compétition)",
				],
				sunday: [],
			},
		],
		ClubEvent: "",
		cover: "images/Senseis/bernardDelhez.jpg",
		pictures: [
			"/images/Dojos/SenNoSen/SenNoSenCarrousel2.jpg",
			"/images/Dojos/SenNoSen/SenNoSenCarrousel1.jpg",
			"/images/Dojos/SenNoSen/SenNoSenCarrousel3.jpg",
			"/images/Dojos/SenNoSen/SenNoSenCarrousel4.jpg",
			"/images/Dojos/SenNoSen/SenNoSenCarrousel5.jpg",
		],
	},
];
export default DojoData;
