const karatekasData = [
	{
		id: "2001",
		club: "Hombu Dojo",
		address: [
			{
				street: "Krijgsbaan",
				number: "39",
				city: "Mortsel",
				postCode: "2640",
				province: "Provincie Antwerpen",
				country: "België",
				lat: "51.1757656",
				lng: "4.4539556",
			},
		],
		contact: [
			{
				email: " stephane.castrique@gmail.com",
				phone: "0032 478 30 16 13",
				website: "http://www.honbu-dojo.be",
			},
		],
		socialNetwork: {
			facebook: "",
			instagram: "",
			youtube: "",
			tiktok: "",
			snapchat: "",
			pinterest: "",
			twitter: "",
		},
		karateka: {
			name: "Stéphane Castrique",
			rank: "6e Dan - Renshi",
			position: "Hombu Dojo Hoofdinstructeur",
			skifPosition: "SKIF-B Hoofdinstructeur",
			yudanshaKai: "Membre du SKIF-B YŪDANSHA KAI",
			pic: "/images/Dojos/HombuDojo/Castrique-Stephane.jpeg",
			town: "Mortsel",
			mention: "",
			studentOf: "",
			ownStudent: {
				student1: "",
				student2: "",
				student3: "",
			},
		},
		competition: {
			worldChampionship: "",
			europeanChampionship: "",
			belgiumChampionship: "",
		},
		family: {
			brotherSister: "Sabine Castrique, 5th Dan & World champion Kata - National Coach Kata",
			wifeHusband: "Kazuyo Takase, 4th Dan & European vice champion kata",
			child1: "Kentaro Castrique, 2nd Dan & World champion Kumite",
			child2: "Kojiro Castrique, 1st Dan & European champion Kumite",
			child4: "",
		},
		cover: "images/senseis/stephaneCastrique.jpg",
		pictures: [
			"/images/Karatekas/StephaneCastrique/StephaneCastrique1.webp",
			"/images/Karatekas/StephaneCastrique/StephaneCastrique2.webp",
			"/images/Karatekas/StephaneCastrique/StephaneCastrique3.webp",
		],
		referee: {
			nationalLevel: "A",
			internationalLicenceKata: "A 'KŌTŌ-CHŌ'",
			internationalLicenceKumite: "A 'KŌTŌ-CHŌ'",
			addComment: "member or the skief Board",
		},
	},
	{
		id: "2002",
		club: "Poseidon",
		address: [
			{
				street: "Av. des Vaillants",
				number: "4",
				city: "Woluwe-Saint-Lambert",
				postCode: "1200",
				province: "Province Bruxelles-Capitale",
				country: "Belgique",
				lat: "50.8435794",
				lng: "4.4194461",
			},
		],
		contact: [
			{
				email: "skif.poseidon@hotmail.com",
				phone: "0032 488 25 65 71",
				website: "http://skif-poseidon.com",
			},
		],
		socialNetwork: {
			facebook: "",
			instagram: "",
			youtube: "",
			tiktok: "",
			snapchat: "",
			pinterest: "",
			twitter: "",
		},
		karateka: {
			name: "Achour Bakkioui",
			rank: "7e Dan",
			position: "Chef Instructeur au Poseidon Dojo",
			skifPosition: "Président SKIF-B YŪDANSHA KAI",
			yudanshaKai: "Président SKIF-B YŪDANSHA KAI",
			pic: "/images/Dojos/Poseidon/AchourB.jpg",
			town: "Woluwe-Saint-Lambert",
			mention: "",
			studentOf: "",
			ownStudent: {
				student1: "",
				student2: "",
				student3: "",
			},
		},
		competition: {
			worldChampionship: "",
			europeanChampionship: "",
			belgiumChampionship: "",
		},
		family: {
			brotherSister: "",
			wifeHusband: "",
			child1: "Sephora Bakkioui 2nd Dan",
			child2: "",
			child4: "",
		},
		cover: "images/Senseis/achourBakkioui.jpg",
		pictures: [
			"/images/Dojos/Poseidon/KanazawaBrothersAchour.jpg",
			"/images/Karatekas/Achour/AchourB1.webp",
			"/images/Karatekas/Achour/AchourB2.webp",
			"/images/Karatekas/Achour/AchourB3.webp",
			"/images/Karatekas/Achour/AchourB4.webp",
			"/images/Karatekas/Achour/AchourB5.webp",
		],
		referee: {
			nationalLevel: "A",
			internationalLicenceKata: "A 'KŌTŌ-CHŌ'",
			internationalLicenceKumite: "A 'KŌTŌ-CHŌ'",
			addComment: "Chef Arbitres Belgium (fr)",
		},
	},
];
export default karatekasData;
